pvlib: include('pvlib')
api: str()
timezone: str()
walls: list(include('wall'), min=1)
---
pvlib:
  coordinates: include('coordinates')

coordinates:
  lat: num()
  long: num()
  alt: int()

wall:
  wall:
    name: str()
    in: int()
    out: int()
    blinds: list(include('blind'), required=False)

blind:
  blind:
    name: str()
    device-id: str()
    device-typ: enum('SHELLY')
    in: int(required=False)
    out: int(required=False)
    tilt_time: num(required=False)
    triggers: list(include('Trigger'), required=False)

Trigger: any(include('TriggerStr'), include('TriggerObj'))

TriggerStr: enum('SUNRISE', 'SUNSET', 'SUNIN', 'SUNOUT')

TriggerObj: any(include('TIME'), include('SUNRISE'), include('SUNSET'), include('SUNIN'), include('SUNOUT'), include('AZIMUTH'), include('ELEVATION'), include('POSITION'))

TIME:
  TIME:
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'))
    time: str()
    offset: int(required=False)

SUNRISE:
  SUNRISE:
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

SUNSET:
  SUNSET:
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

SUNIN:
  SUNIN:
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

SUNOUT:
  SUNOUT:
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

AZIMUTH:
  AZIMUTH:
    azimuth: int()
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

ELEVATION:
  ELEVATION:
    elevation: int()
    direction: str(any('RISE', 'SET'))
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'), required=False)
    offset: int(required=False)

POSITION:
  POSITION:
    azimuth: int()
    elevation: int()
    direction: str(any('RISE', 'SET'))
    task: str(any('OPEN', 'CLOSE', 'TILT', 'HALF'))
    offset: int(required=False)